name: Deploy to development-server-1

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_GITHUB_AWS }}

      - name: SSH to development-server-1 
        run: |
          ssh -o StrictHostKeyChecking=no githubactions@${{ secrets.AWS_DEV_SERVER_1_IP }} << 'EOF'
            cd /var/www/Project1/halasky
            eval $(ssh-agent -s)
            ssh-add ~/.ssh/SSH_AWS_GITHUB
            git stash
            git pull origin development
            pm2 restart halasky --update-env || pm2 start index.js --name halasky
          EOF

          
