name: Deploy to development

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_GITHUB_AWS }}

      - name: SSH to development
        run: |
          ssh -o StrictHostKeyChecking=no githubactions@${{ secrets.AWS_DEV_SERVER_1_IP }} << 'EOF'
            cd /var/www/Project1/halasky
            git pull origin development
            npm install
            npm run db:migrate
            pm2 restart halasky --update-env
          EOF

          
